---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

driver_config:
  network:
  - ["forwarded_port", {guest: 8080, host: 8080}]

provisioner:
  name: chef_solo
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.5

suites:
  - name: default
    run_list:
      - recipe[provision::vim]
      - recipe[provision::mc]
      - recipe[provision::htop]
      - recipe[provision::mysql-server]
      - recipe[provision::hello-world]            
      - recipe[provision::jenkins]            
      - recipe[provision::jenkins_configure]
      - recipe[provision::jenkins_manage]
      - recipe[provision::docker]            
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
